### ISSUE TITLE
The replies breaks the "3 dots button" functionality 

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#1]
When you reply an email previously replied, "3 dots button" stop working properly and you can't show previous messages.

![image](https://user-images.githubusercontent.com/8724844/32487322-a9c560de-c3a9-11e7-8a87-809829c1743b.png)

When you click on "3 dots button" nothing happen.

**Comment by burhan-project-manager** [comment]
Can you please clarify it? I am not able to understand it.

**Comment by jorge9200** [comment]
You send an email to Laura, Laura reply you and when you reply laura again THAT message breaks "3 dots button" functionality.

You press it and doesn't work

**Comment by burhan-project-manager** [comment]
It is fixed!

**Comment by jorge9200** [comment]
@Robby2023 review it please!

**Comment by Robby2023** [comment]
It seems it's working now
