### ISSUE TITLE
Sometimes it sends incomplete content

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#10]
Sometimes when you send an email for some reason send a version that does not include everything you've written, as if the way a version was saved and sent that instead of the last:

Email sent
![vlcsnap-2017-11-03-12h41m03s680](https://user-images.githubusercontent.com/8724844/32488389-b35dab76-c3ac-11e7-9311-57f36dd648e5.png)

Email received
![image 7](https://user-images.githubusercontent.com/8724844/32488415-cd29cc24-c3ac-11e7-9009-efe342e358b1.png)

**Comment by burhan-project-manager** [comment]
This is also fixed with previous issue.

**Comment by jorge9200** [comment]
@Robby2023 test it please

**Comment by Robby2023** [comment]
Yes, seems fixed!
