### ISSUE TITLE
Sometimes it takes a long time to send an email

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#11]
Replies especially

**Comment by burhan-project-manager** [comment]
We have changed the way draft is saving. It is fixed now.

**Comment by jorge9200** [comment]
@Robby2023 test it please

**Comment by burhan-project-manager** [comment]
Tested!

See video 
https://drive.google.com/file/d/1lrvPD6h1CQWiR9QXLABD2anqBJlk6NTT/view

**Comment by jorge9200** [comment]
It seems to work properly! @Robby2023 please take a look before closing it.

**Comment by Robby2023** [comment]
Nice!
