### ISSUE TITLE
If the app is closed the badge of the dock icon is not updated

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#12]
When the app is open and you receive a new email the badge of the dock is updated correctly but if the app is closed then it does not move

You have to use service.js (Ask how)

**Comment by burhan-project-manager** [comment]
How? :)

**Comment by jorge9200** [comment]
You have to add a new script to your static folder, and declare it on info.json like this:

Example of Cosmos app:
![image](https://user-images.githubusercontent.com/8724844/32491140-e5de34b8-c3b5-11e7-826a-9a831d068635.png)

Then this script will be executing always on the background, there you can listen for events and update the badge of the app.

Be careful, because this script also will be executed when the app is opened. So it can be bugs of duplicated listeners on main script and service script.

**Comment by burhan-project-manager** [comment]
We have added "service.js" in info.json but that file is not executing in background.
We have placed service.js file in same location as scripts.js

**Comment by jorge9200** [comment]
have you set it on info.json? Can you show me how?

**Comment by burhan-project-manager** [comment]
Yes placed in info.json

![image](https://user-images.githubusercontent.com/28291997/33064682-55b3222c-cec8-11e7-838b-dab01e0dccdc.png)

**Comment by jorge9200** [comment]
let me test it!

**Comment by jorge9200** [comment]
I can't find your service.js
![image](https://user-images.githubusercontent.com/8724844/33067406-5625a8b6-ceae-11e7-8994-08e6c80300ad.png)

**Comment by burhan-project-manager** [comment]
Strange

It is within script.js

![image](https://user-images.githubusercontent.com/28291997/33070903-64034286-cedb-11e7-908e-a53ec8616013.png)

**Comment by jorge9200** [comment]
strange, let me check again

**Comment by jorge9200** [comment]
totally my fault, I forgot you have to include service into permissions like this:
![image](https://user-images.githubusercontent.com/8724844/33072574-5964c180-cec0-11e7-9e8f-0884d2471909.png)

**Comment by burhan-project-manager** [comment]
Added and it is working now.
But it is only triggering once when page loads. Isn't it should trigger again and again in background?

**Comment by jorge9200** [comment]
Yes, it only trigger once. You should put the event handlers there and anytime a mail is sent or received it should do the behavior you have setted.

**Comment by burhan-project-manager** [comment]
@jorge9200 badge is updating now using event handlers. 
When app is closed, we are only updating badge, not showing banner! Is that ok?

**Comment by jorge9200** [comment]
you also have to fire the banner when event is handled, in the same code area as badge update

**Comment by burhan-project-manager** [comment]
Banner is also fired!

**Comment by jorge9200** [comment]
yes now it firing! issue fixed
