### ISSUE TITLE
Do not launch banner when you receive a new mail

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#13]
Upon receiving a new email the badge of the dock icon is updated and also inside the app but nevertheless is not launching a received mail banner

**Comment by burhan-project-manager** [comment]
Currently it is launching a banner whenever you receive new email. Do you want to stop showing that banner?

**Comment by burhan-project-manager** [comment]
We are now showing banner on new email.

**Comment by jorge9200** [comment]
When you recieve new emails is not showing the banner on upper right corner. The app have to show them always (app opened and app closed) actually it never shows it.

**Comment by burhan-project-manager** [comment]
Banner is launching when app is opened. 

When app is closed it should launch. It will be fixed with https://github.com/Inevio/Gmail/issues/12

**Comment by jorge9200** [comment]
It seem its only launching and refreshing we you have selected the receiver account. If you are on other account a some mail is sent to another one it doesn't refresh (banner & badge)

**Comment by burhan-project-manager** [comment]
Yes you are right. Again  it will be fixed with #12

**Comment by jorge9200** [comment]
I'll close this one when #12 is fixed then

**Comment by jorge9200** [comment]
#12 is closed so...
