### ISSUE TITLE
When opening it does not come out centered

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#14]
Nothing else to open the app seems that it opens with a size and then it expands to the big one, that causes that when opening the app it is not centered:

You have to specify on info.json the initial width and height of the app

**Comment by burhan-project-manager** [comment]
In that case initial with (Login screen) will be bigger than design that was provided. Please confirm.

**Comment by jorge9200** [comment]
you are right, let me check

**Comment by jorge9200** [comment]
Try changing the app size before opening, asking on server.js if the user is logged or not. Then probably u wont have that problem

**Comment by burhan-project-manager** [comment]
We are setting size in scripts.js
When user logged in we change its size but because our script can't access "window" object so we can't place it in correct position.

**Comment by jorge9200** [comment]
You have a method on our api to set the position of the view:

`api.view.setPosition(x, y)`

**Comment by burhan-project-manager** [comment]
Cool. It was implemented!

**Comment by jorge9200** [comment]
perfect, but can you do it on server.js script or start.js script (this is another special script you can use, it runs just before app view is launched). 

![image](https://user-images.githubusercontent.com/8724844/33118430-1dc284da-cf6c-11e7-9f2c-82ed44b81fff.png)

on start.js script you will have a method start() to specify when are you finish with previous calculations and you want to launch the view and pass the control to script.js script.

I suggest doing this on one of those files because when you open the app, you can see the jump it makes correcting its position. It would be wonderful if it calculates the position before launching the view, to make this change invisible to the user.

**Comment by burhan-project-manager** [comment]
@jorge9200  it is implemented accordingly.

**Comment by jorge9200** [comment]
done
