### ISSUE TITLE
When you click on attachment it have to give the option to download to horbito

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#15]
It automatically download to your pc. You have to trigger a popup and ask pc or horbito and if user selects horbito you have to user api.fs.selectDestination() function to ask for a destination and download the file.

**Comment by burhan-project-manager** [comment]
Jorge, give us latest documentation  of selectDestination() method.

**Comment by jorge9200** [comment]
You are going to need 2 methods:

```
            var options = {
                title : 'Select destiny for the file',
                mode : 'file',
                name : fileName
            };

            api.fs.selectDestiny(options, function(error, response) {
```

and then to upload to horbito:

![image](https://user-images.githubusercontent.com/8724844/32491871-8dc66eaa-c3b8-11e7-92b7-d6ce52eda9d4.png)
(yes we are starting with our doc, you can see it here: https://docs.horbito.com/api-integration-gmail.html#f-fileToHorbito)

The folderId you get it from selectDestiny() response

**Comment by burhan-project-manager** [comment]
We have implemented it but there is a confusion about "messageId" parameter of fileToHorbito() method.
Is it gmail account's email address or email of main account of Horbito?

**Comment by jorge9200** [comment]
Nacho will answer you what you have to send

**Comment by icastillejogomez** [comment]
![captura de pantalla 2017-11-21 a las 3 41 52 pm](https://user-images.githubusercontent.com/16567802/33078308-885ded9c-ced2-11e7-945d-f821be63ea40.png)
![captura de pantalla 2017-11-21 a las 3 39 35 pm](https://user-images.githubusercontent.com/16567802/33078212-3f2d31f0-ced2-11e7-894b-6a319de1da90.png)

the messageId is the unique identifier for mail. Yo can get it when you call listThreads. 

![captura de pantalla 2017-11-21 a las 3 41 43 pm](https://user-images.githubusercontent.com/16567802/33078298-8634e9a8-ced2-11e7-9f4c-63bb11ac93b7.png)

**Comment by burhan-project-manager** [comment]
This task is done with #16

**Comment by jorge9200** [comment]
done
