### ISSUE TITLE
The attachments box

### ISSUE THREAD

**Issue by tavi004** [Inevio/Gmail#16]
- When you click on the attachments box there should trigger an alert/popup asking you whether you'd like to download the file to you computer or horbito. Right now it does nothing. 

- The design of the attachments should be adjusted to look like this: 
![image](https://user-images.githubusercontent.com/3248361/33079574-40305862-ced6-11e7-8fc7-abb03fe272d5.png)

With the white icons and the horbito logo not Drive. Here you have the assets 
[assets-attachments.zip](https://github.com/Inevio/Gmail/files/1491837/assets-attachments.zip)

**Comment by burhan-project-manager** [comment]
There are two buttons, one for download and other for horbito. I don't think there is need of asking again if you want to download file to computer or horbito.

User can simply click on "Download" icon or "Horbito" icon.

We need to change icons.

**Comment by jorge9200** [comment]
Ok, but then please change the default behavior of clicking on any part of the square to -> Download to horbito (This has to be the default behavior)

**Comment by burhan-project-manager** [comment]
@jorge9200 it is implemented accordingly.

**Comment by jorge9200** [comment]
done!
