### ISSUE TITLE
Sometimes content of an email is not shown

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Gmail#17]
Sometimes when you open an email it doesn't show the content of the message:

![image](https://user-images.githubusercontent.com/1384919/33135069-ae1def4e-cfa1-11e7-86e8-404a96863259.png)

**Comment by burhan-project-manager** [comment]
It should not do this now!
We have worked a lot on iframe height issue.

If you see this bug again, forward that message to me. I will debug it.

**Comment by jorge9200** [comment]
It seems corrected, @Robby2023 can you take a final look of it?

**Comment by Robby2023** [comment]
Seems to work pretty well, let's close!
