### ISSUE TITLE
Every time I reply to a mail it says "undefinedundefinedundefinedundefined"

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Gmail#18]
![image](https://user-images.githubusercontent.com/1384919/33166107-60ceab3c-d039-11e7-9f92-e8b920f21d68.png)

**Comment by burhan-project-manager** [comment]
We have tried very much but couldn't  re-generate this error.
Can you please provide steps that you are following that generates this error?

**Comment by jorge9200** [comment]
@Robby2023 please, help @burhan-project-manager to replicate this error

**Comment by Robby2023** [comment]
It's not happening now, it seems fixed
