### ISSUE TITLE
no errors handling and revoked token actions

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/Gmail#19]
1. you have to handle all errors in app code.

2. If "REVOKED USER TOKEN" is returned in error (all errors in app) you must show the oauth initial process pop-up
![bug4](https://user-images.githubusercontent.com/16567802/33234651-2b54a09e-d22b-11e7-9c3f-bcbfb0372d41.png)
![bug3](https://user-images.githubusercontent.com/16567802/33234652-2b73de8c-d22b-11e7-8226-866dac122ed5.jpeg)
![bug2](https://user-images.githubusercontent.com/16567802/33234653-2b8d3f62-d22b-11e7-8a41-1bb004b4d02c.jpeg)
![bug1](https://user-images.githubusercontent.com/16567802/33234654-2ba5a85e-d22b-11e7-9a3d-945621095f8c.png)

**Comment by burhan-project-manager** [comment]
@jorge9200  there is a problem in `listAccount` API.

If we have more than 1 accounts and any ONE account has expired token then `listAccount` function is returning `error` of 401 in error argument. 

Although other accounts are correct but it is returning `null` against account.

So ideally it should return error in each account. What do you think.

**Comment by icastillejogomez** [comment]
@burhan-project-manager okay, I'm going to make you an end-point to solve this.

**Comment by jorge9200** [comment]
@icastillejogomez thank you so much, tell us when is done

**Comment by icastillejogomez** [comment]
You can call listDisableAccounts method on api.integration.gmail variable. In this screenshot and in your start.js file (static directory) you can find the example code.

![gmail2](https://user-images.githubusercontent.com/16567802/33464768-5df8d854-d644-11e7-920e-50eaee07d0f9.png)

you can see the results:

![gmail3](https://user-images.githubusercontent.com/16567802/33464810-95ee4c6c-d644-11e7-9c67-0901bac4e48b.png)

when i completed the oauth process:

![gmail4](https://user-images.githubusercontent.com/16567802/33464816-a5617048-d644-11e7-8d64-080df511f332.png)

add the patch in this part too:

![gmail2](https://user-images.githubusercontent.com/16567802/33464838-c25e8dc0-d644-11e7-8baa-e069de9386ac.png)

thx!

**Comment by burhan-project-manager** [comment]
Thanks, it is implemented accordingly.
