### ISSUE TITLE
Replies sets to much white space 

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#2]
![image 1](https://user-images.githubusercontent.com/8724844/32487519-2d01e56c-c3aa-11e7-9f82-17fa00a9aa76.png)

If you click on "3 dots button" it sets more white space.

![image 2](https://user-images.githubusercontent.com/8724844/32487545-42df6db4-c3aa-11e7-99bd-26053335509d.png)

**Comment by burhan-project-manager** [comment]
It was done!

**Comment by jorge9200** [comment]
@Robby2023 review it please!

**Comment by Robby2023** [comment]
Seems pretty good, let's close!
