### ISSUE TITLE
The small badge on the bottom left corner doesn't update in real time

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Gmail#21]
This one:

![image](https://user-images.githubusercontent.com/1384919/33265343-94707304-d371-11e7-9aa6-ecb2a39f53d3.png)

Sending the video right now through Skype

**Comment by burhan-project-manager** [comment]
Yes it was creating problem with other account. 
It is fixed now!

**Comment by jorge9200** [comment]
give it a test @Robby2023 please!

**Comment by jorge9200** [comment]
seems working
