### ISSUE TITLE
Add an intro before the signature

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Gmail#22]
When writing an email, the signature is too close to the message, we should add an additional intro before the signature so the message is separated from the signature:

![image](https://user-images.githubusercontent.com/1384919/33265396-d52331fc-d371-11e7-9ddf-d0e3b27240f4.png)

**Comment by burhan-project-manager** [comment]
Intro added!

![image](https://user-images.githubusercontent.com/28291997/33302516-8198f9ce-d41e-11e7-8e79-03092b2fbcc9.png)

**Comment by jorge9200** [comment]
thanks closed
