### ISSUE TITLE
Increase from 20px to 28px the top padding on the message

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Gmail#23]
Right now the message is too close to the top bar:

![image](https://user-images.githubusercontent.com/1384919/33265527-563c915c-d372-11e7-86ef-56facccb7fd7.png)

If we increase the top padding from 20px to 28px it's much better:

![image](https://user-images.githubusercontent.com/1384919/33265556-6c90d38c-d372-11e7-8a6e-1407f5fafe9e.png)

**Comment by burhan-project-manager** [comment]
It is fixed!

**Comment by jorge9200** [comment]
FIXED
