### ISSUE TITLE
No hover state on some buttons

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Gmail#24]
Some buttons don't have a hover state:

![image](https://user-images.githubusercontent.com/1384919/33265792-3c7735a0-d373-11e7-84b7-a2593c637f9b.png)

![image](https://user-images.githubusercontent.com/1384919/33265810-501cbbca-d373-11e7-9778-bcb14c092f68.png)

**Comment by burhan-project-manager** [comment]
Hover state is implemented on almost all icons.

**Comment by jorge9200** [comment]
Close it when all buttons especified by @Robby2023 have hover state

**Comment by Robby2023** [comment]
Reassigning to our desginer @tavi004

**Comment by tavi004** [comment]
The attachment hover is horrible 
![image](https://user-images.githubusercontent.com/3248361/33607106-26476676-d9c0-11e7-9eca-0ec366fc01de.png)

It should look more like this
![image](https://user-images.githubusercontent.com/3248361/33607135-4be425b8-d9c0-11e7-866b-87423c5edac2.png)

I attach you the asset with all the spaces so you can center the image in the box. The box should be 34x34px with 6px radius #e5e5e5.
[attach-icon.zip](https://github.com/Inevio/Gmail/files/1531106/attach-icon.zip)

The delete email hover is awful too, it should be the same as the attach, but 24x24px
![image](https://user-images.githubusercontent.com/3248361/33607378-381d6264-d9c1-11e7-95bb-e3df0ea14f7a.png)

**Comment by burhan-project-manager** [comment]
Attachment and delete buttons are replaced now!

**Comment by Robby2023** [comment]
When you hover over the arrows to move to the next page/previous page both get the hover effect instead of only the one you actually want to click.

Also, if the icon is grey because you can't go to the previus page or next page (because you're at the start or at the end) it shouldn't have a hover effect.

**Comment by burhan-project-manager** [comment]
@Robby2023  It is fixed!
