### ISSUE TITLE
Retina problems

### ISSUE THREAD

**Issue by tavi004** [Inevio/Gmail#25]
On retina screens the icons look bad: 
![image](https://user-images.githubusercontent.com/3248361/33347917-ccd98a86-d494-11e7-8c36-fe0b6d38a7f4.png)
![image](https://user-images.githubusercontent.com/3248361/33347935-db2f440e-d494-11e7-9ce2-682dc2387393.png)
![image](https://user-images.githubusercontent.com/3248361/33347942-df487344-d494-11e7-9fbb-272e9e0a03c2.png)
![image](https://user-images.githubusercontent.com/3248361/33348019-0fa0c1a4-d495-11e7-835d-84b5d8ad5dbb.png)

**Comment by jorge9200** [comment]
You can solve it, with 3 steps:
1. Save on /static the double size assets
2. Name them like their originals but with @2x (Ej: avatar@2x.png)
3. Set on css background-size: "original-size" when you use images (If normal asset is 10x10 and @2x is 20x20 -> background-size: 10px 10px)

**Comment by jorge9200** [comment]
If you need some @2x assets, you can ask @tavi004

**Comment by burhan-project-manager** [comment]
Yes we need. 
@tavi004  please send me those assets.

**Comment by tavi004** [comment]
[assets retina.zip](https://github.com/Inevio/Gmail/files/1526497/assets.retina.zip)

**Comment by burhan-project-manager** [comment]
Thanks @tavi004, but we have different sprite and need @2x for it:
https://static.horbito.com/app/522/gernalBlack.png

**Comment by tavi004** [comment]
I cannot extract the @2x version of that same sprite so you'll have to use the sprites provided that do have the @2x version, because are the ones used by gmail.com. And the custom icons that are not from gmail are not in the sprite, are outside, like the search icon or the arrow down icons. 

[ASSETS.zip](https://github.com/Inevio/Gmail/files/1531018/ASSETS.zip)

**Comment by burhan-project-manager** [comment]
We have created new sprite because old one was missing some icons.
It is implemented now!

@tavi004 take a look please!

**Comment by jorge9200** [comment]
It looks great, only remain one icon:

![image](https://user-images.githubusercontent.com/8724844/33881021-caab8486-df33-11e7-9780-bd184d3429c1.png)

**Comment by jorge9200** [comment]
this arrow

**Comment by burhan-project-manager** [comment]
It is also fixed!

**Comment by jorge9200** [comment]
It is fused with the text now 
![image](https://user-images.githubusercontent.com/8724844/33939660-4b10716c-e00c-11e7-994d-599b37f036fc.png)

**Comment by burhan-project-manager** [comment]
It is fixed now again!

**Comment by jorge9200** [comment]
seems right!
