### ISSUE TITLE
Message actions popup not working 

### ISSUE THREAD

**Issue by burhan-project-manager** [Inevio/Gmail#26]
- Hover not working on this menu
- "Delete this message" not deleting message
- "Mark unread" going to 2nd page
- Menu not hiding when clicking outside

![image](https://user-images.githubusercontent.com/28291997/33412888-1d86a8ee-d5b0-11e7-866d-2182db1ab81f.png)

**Comment by burhan-project-manager** [comment]
It is fixed now!

**Comment by jorge9200** [comment]
perfect
