### ISSUE TITLE
Text on init popup is not showing right

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#27]
![image](https://user-images.githubusercontent.com/8724844/33422648-aa6cb018-d5b6-11e7-8013-0321062f18d1.png)

Can you please adjust "more or less" this text line jumps on english and spanish. Only to not make wierd line jumps.

**Comment by jorge9200** [comment]
![image](https://user-images.githubusercontent.com/8724844/33422720-e0d73bbe-d5b6-11e7-9eae-58592cd26fce.png)

**Comment by burhan-project-manager** [comment]
You need to add `<br>`  within translation text because some translations can take more space so it is better to manage `<br>` within translation.

Check it now.

![image](https://user-images.githubusercontent.com/28291997/33425242-efb3b7f6-d5df-11e7-8490-0221449db466.png)

**Comment by jorge9200** [comment]
@tavi004 take a look!

**Comment by tavi004** [comment]
In english it looks good except:

The text should have line-height: 26px

And in spanish it should look like this:
![image](https://user-images.githubusercontent.com/3248361/33545734-5ca21b3a-d8df-11e7-82ec-d88d8a007b0f.png)


Spanish text: "Accede a tu correo directamente desde horbito.
Puedes adjuntar y guardar archivos a tu cuenta
sin tener que descargarlos a tu ordenador."

**Comment by burhan-project-manager** [comment]
It is modified!

**Comment by jorge9200** [comment]
solved
