### ISSUE TITLE
Sometimes text is misplaced

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Gmail#28]
Sometimes the content of an email appears very close to the left side instead of the correct position:

![image](https://user-images.githubusercontent.com/1384919/33432087-f8aedd8a-d5d6-11e7-95de-39ef6b4ec5a7.png)

**Comment by Robby2023** [comment]
We just realized the problem is when the sender doesn't have a name. Right now it just removes the field from the app instead of using the text before "@" like Gmail does.

**Comment by burhan-project-manager** [comment]
We are not able to re-produce this error. 

@Robby2023 Please check it now! It might be due to email tag that gmail was returning with name. We have removed it.

**Comment by Robby2023** [comment]
It's still happening:

![image](https://user-images.githubusercontent.com/1384919/33549993-ab4ab028-d8ec-11e7-92dd-02d856af7b1a.png)

![image](https://user-images.githubusercontent.com/1384919/33550004-b59c2098-d8ec-11e7-902f-c4328fe85df5.png)

Here is what Gmail displays:

![image](https://user-images.githubusercontent.com/1384919/33550033-cb3191e0-d8ec-11e7-97df-6f1d63050aed.png)

![image](https://user-images.githubusercontent.com/1384919/33550042-d3a1da6a-d8ec-11e7-82d2-c0e89cf12dff.png)

**Comment by Robby2023** [comment]
![image](https://user-images.githubusercontent.com/1384919/33550079-ec9d3a32-d8ec-11e7-887a-898654e67e52.png)

**Comment by Robby2023** [comment]
Here is what Gmail shows:

![image](https://user-images.githubusercontent.com/1384919/33550150-2e61ebf2-d8ed-11e7-8dae-7be2d2720401.png)

**Comment by burhan-project-manager** [comment]
@Robby2023  you are right. It is fixed now!

**Comment by Robby2023** [comment]
Fixed!!!
