### ISSUE TITLE
When you read an email the badge on the app icon doesn't update

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Gmail#30]
This one:

![image](https://user-images.githubusercontent.com/1384919/33622139-3fe94144-d9ed-11e7-9277-d4d2511dbb24.png)

**Comment by burhan-project-manager** [comment]
It is fixed!

**Comment by Robby2023** [comment]
Now there is a different problem:

When you click on an unread email, sometimes it updates both badges (small and big one) but sometimes it doesn't:

(In this image you can see the number that appears on Inbox is not the same as the number shown in both badges)
![image](https://user-images.githubusercontent.com/1384919/33715522-275c8bb0-db53-11e7-879f-9445d35698b1.png)

**Comment by Robby2023** [comment]
It also happens the other way round:

![image](https://user-images.githubusercontent.com/1384919/33882254-c9f3b960-df37-11e7-852e-0e628d2a4a5c.png)

**Comment by burhan-project-manager** [comment]
Yeah it was creating problem when we are not in INBOX.
It is fixed now!

**Comment by Robby2023** [comment]
It seems fixed!
