### ISSUE TITLE
Error when I try to forward an email

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/Gmail#31]
Please, let me know your email address to send you a conflictive email. We are trying to forward it and browser crashed! We think that the reason is a infinity loop in your code.

**Comment by burhan-project-manager** [comment]
burhan.khan@elementarylogics.com

**Comment by icastillejogomez** [comment]
I have just sended it to you

**Comment by burhan-project-manager** [comment]
Received. 
Yes it is stuck at that message. We will check it.

**Comment by icastillejogomez** [comment]
pfct =D thx!

**Comment by burhan-project-manager** [comment]
@icastillejogomez we have found the bug, it is due to WYSIWYG editor
http://www.niceonecode.com/Q-A/JAVAScript/JQuery/Jquery-text-editor-(jqte)-hangs-the-browser-when-writing-big-text-data/20380

We will try to find a solution tomorrow.

**Comment by burhan-project-manager** [comment]
We have implemented TinyMCE because it supports iframe.
But there are some events that needs modifications like three dots ... 

We will do it on next working day.

**Comment by icastillejogomez** [comment]
Now, when I forward an email the original content body don't send it. Can you look at that?

**Comment by burhan-project-manager** [comment]
@icastillejogomez 

updateUserDraft works fine in normal condition but if we try to save big email, it has strange behavior.

It continuously tries to connect with sockets.

![image](https://user-images.githubusercontent.com/28291997/34825175-33ad08de-f6f3-11e7-826e-548b10104dda.png)

And after some time, it throws this error:
![image](https://user-images.githubusercontent.com/28291997/34825189-470c1960-f6f3-11e7-9fbd-9d800b5578a1.png)

**Comment by icastillejogomez** [comment]
Thanks Burhan, I will try to find the reason of this.

**Comment by javiergarmon** [comment]
The issue is our court, we'll fix it as soon as possible. After a few inquiries we've found this request overcome the websocket's frame maximum size.

Apparently It's a server configuration option so I hope it could be solved really soon.

**Comment by javiergarmon** [comment]
It doesn't seem enough to increase the allowed frame size. I've to investigate a little bit more.

**Comment by javiergarmon** [comment]
Ok guys, it's fixed 😉  @icastillejogomez what's next?

**Comment by icastillejogomez** [comment]
Great! It's fixed :D
