### ISSUE TITLE
Arrow not showing correctly

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#32]
In normal & retina this button, doesn't show correctly the arrow asset:

![image](https://user-images.githubusercontent.com/8724844/33939878-1ab09f78-e00d-11e7-9d96-ba49fb7e22dd.png)

**Comment by jorge9200** [comment]
![image](https://user-images.githubusercontent.com/8724844/33939890-25ea5140-e00d-11e7-8be4-8487aadd8554.png)

**Comment by burhan-project-manager** [comment]
Fixed!
