### ISSUE TITLE
Use span instead of a tag

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/Gmail#33]
Download and watch it. http://wz.io/f/6a6QrchV

**Comment by icastillejogomez** [comment]
you have to use css property `cursor: pointer;`

**Comment by burhan-project-manager** [comment]
Did it using span now!

**Comment by icastillejogomez** [comment]
there are no more "a" labels in the whole application?

**Comment by burhan-project-manager** [comment]
I thought you only wants in attachment.
Let us replace all today.

**Comment by icastillejogomez** [comment]
I'm sorry Burhan, I didn't think so. I apologize for the inconvenience.

**Comment by burhan-project-manager** [comment]
All anchor tags are replaced by span with corresponding styles.
