### ISSUE TITLE
Add hover state with dragger to compose container

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#34]
![image_2017-12-18_11-52-22](https://user-images.githubusercontent.com/8724844/34102608-18dee32c-e3ea-11e7-8772-6e5a2eaf80bf.png)

When you hover this container ask if you are dragging an element and if it is, add this style.

**Comment by burhan-project-manager** [comment]
@jorge9200  we are still not able to drag drop files.  
Those drag drop events are not working and this task is dependent on those events.

You said it is working fine. Is it any browser specific?

**Comment by burhan-project-manager** [comment]
Hover state is added!

**Comment by jorge9200** [comment]
@tavi004 review it and close it if it is ok please

**Comment by tavi004** [comment]
The "Drop files here" should have font-weight: 900

And for the dashed border I don't know if it's possible to make the dashes longer and with more space between them.

**Comment by burhan-project-manager** [comment]
It is completed!

**Comment by tavi004** [comment]
When I do the hover it ovelaps with the text format icons 
![image](https://user-images.githubusercontent.com/3248361/34302281-8a88708a-e730-11e7-8ca4-ddf03d80e2d2.png)

**Comment by burhan-project-manager** [comment]
It is fixed!
