### ISSUE TITLE
Compose and respond design

### ISSUE THREAD

**Issue by tavi004** [Inevio/Gmail#36]
# Compose window
![image](https://user-images.githubusercontent.com/3248361/34298964-a922c618-e720-11e7-8090-c3a0435e6840.png)

Apart from all this the Window should be separated 12px from the border of the app and with a shadow:
`  box-shadow: 0px 10px 20px 0px rgba(34, 31, 26, 0.3);`
![image](https://user-images.githubusercontent.com/3248361/34298979-c27ca728-e720-11e7-80ec-bded2c958322.png)
![image](https://user-images.githubusercontent.com/3248361/34299092-5b3e1230-e721-11e7-8e34-446343675dc9.png)

# Respond textbox

Fix the same things like in the compose window +

Fix the avatar already!
![image](https://user-images.githubusercontent.com/3248361/34299109-7a6d1c64-e721-11e7-8504-9a0d08b70186.png)

**Comment by burhan-project-manager** [comment]
Those all are fixed please check.

**Comment by tavi004** [comment]
Fix the avatar! 30x30px![image](https://user-images.githubusercontent.com/3248361/34520935-5570a106-f08b-11e7-859d-17b8d888f615.png)


Delete that shadow and center the icons![image](https://user-images.githubusercontent.com/3248361/34520982-9808b67a-f08b-11e7-83c8-f7d7b482815d.png)

**Comment by burhan-project-manager** [comment]
Which shadow should be deleted? @tavi004

**Comment by tavi004** [comment]
![untitled-1](https://user-images.githubusercontent.com/3248361/34557549-e8bef99e-f13a-11e7-96cf-5e8736ecb202.jpg)

**Comment by burhan-project-manager** [comment]
@tavi004 shadow removed!
Still have confusion about which icon should be in center?

Check current preview
![image](https://user-images.githubusercontent.com/28291997/34775113-d3759c48-f633-11e7-9281-e579b03fb415.png)

**Comment by tavi004** [comment]
Neither of the icons are centred with the button
![image](https://user-images.githubusercontent.com/3248361/34775966-5e8b4b76-f615-11e7-9c25-7e37b0a0a242.png)

**Comment by burhan-project-manager** [comment]
ok it is centered now!
