### ISSUE TITLE
When you attach a big file it always write it at the start of email body

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#4]
It would be wonderful to write it where the cursor was.

![image 3](https://user-images.githubusercontent.com/8724844/32487803-f5c07ec8-c3aa-11e7-99a3-4693bb65d5c1.png)

**Comment by burhan-project-manager** [comment]
We have tried to do this but the plugin that we are using is not allowing us.
Also if anyway we implement it, there is an issue. For example what if my cursor is in middle of any word like "adjuntar".

What we can do is to add a line with margin on bottom and top. Please confirm

**Comment by jorge9200** [comment]
yes, add a line jump after de link to ensure it looks good

**Comment by burhan-project-manager** [comment]
Line jump was added!

**Comment by jorge9200** [comment]
perfect!
