### ISSUE TITLE
Attach file using the attach button doesn't work

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Gmail#40]
If you try to attach a file using the attach button nothing happens (If you attach using drag&drop it works perfect)

**Comment by burhan-project-manager** [comment]
It is working fine now, but again Gmail is giving 404 error when downloading that attachment.
@icastillejogomez fixed it in some previous ticket, but still need to see again.

**Comment by icastillejogomez** [comment]
Works fine now, i don't close it yet to look out it this days
