### ISSUE TITLE
I'm trying to open an email but it just shows "Loading..."

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Gmail#41]
When I try to open an email I've just received it doesn't open, it just shows "Loading..."

![image](https://user-images.githubusercontent.com/1384919/34565533-756e63f0-f15b-11e7-9202-85ddded5f742.png)

On Gmail it opens perfectly:

![image](https://user-images.githubusercontent.com/1384919/34565551-8b8fbbde-f15b-11e7-8f0a-28fa555af65c.png)

**Comment by Robby2023** [comment]
Same problem with a different email:

![image](https://user-images.githubusercontent.com/1384919/34611214-dba377ae-f224-11e7-89e9-fef245fd4d85.png)

**Comment by burhan-project-manager** [comment]
@Robby2023  there was another scenario in which gmail was returning parts inside parts. We have covered it also.

![image](https://user-images.githubusercontent.com/28291997/34775258-55adc384-f634-11e7-962a-22459d9e888e.png)

**Comment by Robby2023** [comment]
Seems fixed!

**Comment by Robby2023** [comment]
It's happening again! It has just happened to a coworker on an email with two attachments:

![photo_2018-01-16_14-58-24](https://user-images.githubusercontent.com/1384919/34992511-b6093270-facd-11e7-9867-9db587c6d70b.jpg)

**Comment by Robby2023** [comment]
Same problem with a different email (one attachment):

![image](https://user-images.githubusercontent.com/1384919/34994232-20adbefc-fad3-11e7-8413-132551952679.png)

**Comment by josemhdez** [comment]
Same problem:

![image](https://user-images.githubusercontent.com/12035376/35046463-5a9f7352-fb97-11e7-9971-047dd7c422a6.png)

**Comment by javiergarmon** [comment]
Related #41

**Comment by burhan-project-manager** [comment]
It is fixed with #51 

If you still see any "loading" issue, please forward that email to me or send me JSON of message.

**Comment by Robby2023** [comment]
Okay, I'll leave this issue opened and update as soon as I have news

**Comment by josemhdez** [comment]
Im still having the issue!

![image](https://user-images.githubusercontent.com/12035376/35103991-d8bb83d6-fc67-11e7-860a-5ecac3c6ff29.png)

**Comment by burhan-project-manager** [comment]
> If you still see any "loading" issue, please forward that email to me or send me JSON of message.
