### ISSUE TITLE
Sometimes the signature doesn't appear

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Gmail#45]
When I click on "Compose" and write a new email, sometimes the signature appears and others it doesn't.

- With signature:

![image](https://user-images.githubusercontent.com/1384919/34938565-1612b44c-f9e9-11e7-8998-c11b6e01ba9b.png)

- Without signature:

![image](https://user-images.githubusercontent.com/1384919/34938544-06c39448-f9e9-11e7-8f35-c6d4243f6152.png)

**Comment by Robby2023** [comment]
It's actually pretty easy to simulate:

- Open app
- Click on compose (it shows signature)
- Close New Message
- Click on compose (now signature doesn't appear)

**Comment by burhan-project-manager** [comment]
It is fixed!

**Comment by Robby2023** [comment]
Seems fixed!
