### ISSUE TITLE
Weird spaces when sending an email

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Gmail#46]
- How the email appears in compose:

![image](https://user-images.githubusercontent.com/1384919/34938688-92bc325c-f9e9-11e7-92cf-eea3004ff929.png)

- How the email is received:

![image](https://user-images.githubusercontent.com/1384919/34938717-a8530500-f9e9-11e7-9671-7a3a6cb880a2.png)

- In Gmail it also appears wrong:

![image](https://user-images.githubusercontent.com/1384919/34938746-b6430f48-f9e9-11e7-9b47-b8e2262861b9.png)

**Comment by burhan-project-manager** [comment]
Fixed!

**Comment by Robby2023** [comment]
Yes!
