### ISSUE TITLE
Wierd hover on add Account plus button

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#50]
Can you add the same ammount of padding to both sides?
![image](https://user-images.githubusercontent.com/8724844/34938901-3518d12c-f9ea-11e7-889c-7ed217be94ee.png)

**Comment by burhan-project-manager** [comment]
@jorge9200 are you talking about counters padding?

**Comment by jorge9200** [comment]
Only about plus button padding, the one which makes the hover shadow it has more padding on the left side than in the right side

![image](https://user-images.githubusercontent.com/8724844/34992500-b0f2c878-facd-11e7-9348-cd5271b95e4d.png)

**Comment by burhan-project-manager** [comment]
It is done!

**Comment by jorge9200** [comment]
fixed
