### ISSUE TITLE
When I start forwarding a message, "undefined" mail is the default recipient

### ISSUE THREAD

**Issue by javiergarmon** [Inevio/Gmail#52]
![screen shot 2018-01-15 at 11 50 50](https://user-images.githubusercontent.com/1794673/34938970-771dc9f6-f9ea-11e7-9f5e-a7a668888184.png)

**Comment by burhan-project-manager** [comment]
It is fixed. We are not getting any undefined now.

Please confirm!

**Comment by javiergarmon** [comment]
It seems fixed but now there is other issue:

Before click it:

![captura de pantalla 2018-01-17 a las 15 19 59](https://user-images.githubusercontent.com/1794673/35047451-42a7472c-fb9a-11e7-9d35-946dc4e3c730.png)

After click it this UI is showed (this should be visible always):

![captura de pantalla 2018-01-17 a las 15 20 03](https://user-images.githubusercontent.com/1794673/35047468-51d00e6e-fb9a-11e7-91f2-4d2edd12fa5c.png)

You have to click again to focus the input.

**Comment by burhan-project-manager** [comment]
@javiergarmon check it now!

**Comment by javiergarmon** [comment]
![install-apache-it-works-port80](https://user-images.githubusercontent.com/1794673/35098690-840af770-fc55-11e7-8087-23a3f965a60c.png)
