### ISSUE TITLE
When you use reply or forward compose way you lose the signature

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#55]

**Comment by icastillejogomez** [comment]
https://github.com/Inevio/Gmail/issues/45

**Comment by burhan-project-manager** [comment]
When we reply or forward, gmail is adding three dots and hiding signature in three dots.
We are doing same thing.

**Comment by jorge9200** [comment]
Yes exactly but we are not adding signature after dots content
![image](https://user-images.githubusercontent.com/8724844/34992143-79379e5a-facc-11e7-90f1-06a0c21e5961.png)

**Comment by burhan-project-manager** [comment]
Gmail is showing signature just after three dots. Do you want signature at end of message?

![image](https://user-images.githubusercontent.com/28291997/35026962-e63c2de2-fb6f-11e7-8c8a-36f1986e9ce8.png)

**Comment by jorge9200** [comment]
Gmail shows it before the message not after, look:
![image](https://user-images.githubusercontent.com/8724844/35042733-0ef45e98-fb8a-11e7-9fdf-87c10fcc0986.png)

So yes please, show it and the end

**Comment by burhan-project-manager** [comment]
I figured out the problem. Actually if we check following checkbox Gmail shows signature on top. Because we can't get that value, we will show signature on bottom. You are right!

![image](https://user-images.githubusercontent.com/28291997/35044397-0d73531c-fbb2-11e7-83ee-c7b33b1196fb.png)

**Comment by burhan-project-manager** [comment]
Signature is added at the end of message in reply/forward message.

**Comment by jorge9200** [comment]
Wow I didn't know about that checkbox, sorry @burhan-project-manager and issue fixed!
