### ISSUE TITLE
When someone answers to my email, his name should appear instead of mine

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Gmail#59]
Let me explain, when someone answers to an email I've sent, it currently shows like this:

![image](https://user-images.githubusercontent.com/1384919/34992400-63408c46-facd-11e7-8bfd-84671dfbae3a.png)

However, it should show the name of the last sender like it does in Gmail:

![image](https://user-images.githubusercontent.com/1384919/34992426-7c6b3f2c-facd-11e7-9829-b40666edf0cb.png)

**Comment by Robby2023** [comment]
Right now my last 5 emails seem to be sent by myself:

![image](https://user-images.githubusercontent.com/1384919/34997036-a91530d8-fadb-11e7-9543-d5960398f85b.png)

**Comment by burhan-project-manager** [comment]
We have tried to follow every scenario of Gmail and it looks good now.

**Comment by Robby2023** [comment]
Seems pretty good!
