### ISSUE TITLE
When you try to reply or forward a big email, the browser crash

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#6]
Emails like spam ones with lot of images and text.

**Comment by burhan-project-manager** [comment]
Can you forward that email to my email address? I will check it in my Gmail why it is crashing?

**Comment by jorge9200** [comment]
@Robby2023 can you please forward Burhan? Ask me for his email

**Comment by Robby2023** [comment]
It doesn't crash now but if I try to reply it says "Sending..." all the time and never sends the email

**Comment by burhan-project-manager** [comment]
We have tried it with different messages but it is working fine.
May be it was testing at the time of development and cause some error?

If you see it again, kindly forward me that email message.

**Comment by burhan-project-manager** [comment]
It seems sometime when we send long message `usersDraftSend` returns following code from server.

`{"error":{"errors":[{"domain":"global","reason":"notFound","message":"Not Found"}],"code":404,"message":"Not Found"}}`

Although draft is saving successfully.

**Comment by jorge9200** [comment]
what can be the reason @icastillejogomez ?

**Comment by icastillejogomez** [comment]
I'm looking the reason

**Comment by icastillejogomez** [comment]
![simplemail](https://user-images.githubusercontent.com/16567802/33862294-4536a700-dee2-11e7-8392-7c55c8f9f9de.jpeg)
![bigmail](https://user-images.githubusercontent.com/16567802/33862295-45517ed6-dee2-11e7-9623-0e3973ab93ec.jpeg)
![attachment](https://user-images.githubusercontent.com/16567802/33862296-456e4ef8-dee2-11e7-9c44-c1d2f25b423e.jpeg)

**Comment by icastillejogomez** [comment]
the new endpoint interface is: getAttachment( messageId, attachmentId, callback )

**Comment by burhan-project-manager** [comment]
It is fixed.

**Comment by jorge9200** [comment]
I cant test it until #35

**Comment by jorge9200** [comment]
seems working
