### ISSUE TITLE
Implement the "added account" event.

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/Gmail#63]
When OAuth process is complete, "added-account" event is send to the app. The way to implement is the same like the others events.

Thank you so much guys, the app is pretty cool. =D

**Comment by burhan-project-manager** [comment]
@icastillejogomez after adding account we are getting this error in popup:

![image](https://user-images.githubusercontent.com/28291997/35084529-3f3cbd5e-fc46-11e7-9040-38f082183471.png)

**Comment by icastillejogomez** [comment]
fixed

**Comment by icastillejogomez** [comment]
Okay. Works perfect! Only another question for you. We saw a second "listAccounts" call. Is it necessary? Could we avoid it?

**Comment by burhan-project-manager** [comment]
We need "listAccounts" when getting all account.

**Comment by icastillejogomez** [comment]
Ok. Perfect. Then I'm going to close it.
