### ISSUE TITLE
Headings, Bold and Italic doesn´t work

### ISSUE THREAD

**Issue by josemhdez** [Inevio/Gmail#66]

**Comment by burhan-project-manager** [comment]
It was due to #39. We have removed reset.css and it is working fine!

**Comment by josemhdez** [comment]
It is not working properly. When you select a heading, th whole text you were writting is swichted to the heading you selected, while in Gmail it statrs to change the text from the moment you select the heading, without changing the rest of the tetxt.

![image](https://user-images.githubusercontent.com/12035376/35215644-2d3a3d08-ff65-11e7-9851-15ae10c6af1f.png)

**Comment by burhan-project-manager** [comment]
Heading tag margin by default so we have removed it.
Also Gmail was using font-size, we also implemented it but in terms of points, like 10pt, 12pt.
