### ISSUE TITLE
Problem with the dates of email conversations

### ISSUE THREAD

**Issue by josemhdez** [Inevio/Gmail#67]
The date in which emails are sent or received, when conversations, are listed wrong. Gmail lists email conversations by the last day you received an answer or when sent, the last day you sent an email. here is listed correctly but the dates it shows belong to the dirst mail crossed with the other person.

![image](https://user-images.githubusercontent.com/12035376/35098567-00ceb680-fc55-11e7-858c-f1b2bc18275a.png)

**Comment by burhan-project-manager** [comment]
It is done!
