### ISSUE TITLE
Regular expression in addresses

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/Gmail#68]
I can try to send a message with an invalid address pattern. Then Gmail responses with an error "Recipient address required".

You have to check with regular expressions all addresses.

https://stackoverflow.com/questions/46155/how-can-you-validate-an-email-address-in-javascript

**Comment by burhan-project-manager** [comment]
Implemented!

Now it will show warning if email is invalid

![image](https://user-images.githubusercontent.com/28291997/35151416-0946eabc-fd40-11e7-97b8-1247c6647a4d.png)

**Comment by icastillejogomez** [comment]
looks fantastic
