### ISSUE TITLE
The date shown in the main view is not always correct

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Gmail#69]
Right now if I look at the dates of the emails that show up on my main view I see this:

![image](https://user-images.githubusercontent.com/1384919/35101952-b10d5a04-fc61-11e7-8fb0-2131f81fdc50.png)

The issue is with those emails that are a response from a previus email, on all of them it should always show the time of the last email received. Here is what it looks like in Gmail:

![image](https://user-images.githubusercontent.com/1384919/35102150-58efb1fe-fc62-11e7-8c93-bdbb31b0b102.png)

**Comment by burhan-project-manager** [comment]
Gmail is showing date of last message. Now we have done the same!

**Comment by Robby2023** [comment]
Perfect!
