### ISSUE TITLE
When I use the tab in the "To:" the cursor disappears

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#7]
If I have the focus on the "To:" and I press the tab, the cursor disappears and if I write, nothing happens. What should happen is that you gave the email you were writing as entered and your cursor followed in the "To:" so you can continue writing more emails and if you press return send you the input of "Subject:"

**Comment by burhan-project-manager** [comment]
It is done!

**Comment by jorge9200** [comment]
fixed
