### ISSUE TITLE
Wrong snippet on conversations

### ISSUE THREAD

**Issue by josemhdez** [Inevio/Gmail#70]
While GMail shows you the body of the mails without having to expand them, the app shows you the contact of tha mail instead of the body.

![image](https://user-images.githubusercontent.com/12035376/35102447-4c3fddfc-fc63-11e7-84ad-f8ddf6baf2e9.png)

![image](https://user-images.githubusercontent.com/12035376/35102504-6d575056-fc63-11e7-96a8-90ad5890e16f.png)

**Comment by burhan-project-manager** [comment]
Its done!
