### ISSUE TITLE
Typography is incorrect

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Gmail#71]
- When you open an email you're using Times New Roman instead of Arial (And I think you're using #000 instead of #222):

![image](https://user-images.githubusercontent.com/1384919/35102611-ab318824-fc63-11e7-8d80-5d6029dbb1f3.png)

Here is how the text appears in Gmail:

![image](https://user-images.githubusercontent.com/1384919/35102636-bbc8b928-fc63-11e7-9715-1b800645b99b.png)

- In the compose window you're using Effra #000 instead of Arial #222 (Also, the link should be blue):

![image](https://user-images.githubusercontent.com/1384919/35102891-87f852ba-fc64-11e7-82d9-87825ddfce79.png)

Here is how the text appears in Gmail:

![image](https://user-images.githubusercontent.com/1384919/35102900-91a584c2-fc64-11e7-9280-6bbb28693be5.png)

- In the main view you're using Lato instead of Arial:

![image](https://user-images.githubusercontent.com/1384919/35103126-48b2e088-fc65-11e7-9ef5-487889cb82ee.png)

Here is how the text appears in Gmail:

![image](https://user-images.githubusercontent.com/1384919/35103147-587c4cac-fc65-11e7-81ca-2a7f6068e3df.png)

**Comment by burhan-project-manager** [comment]
Those points were done!

Previous sent emails may not work properly. But new emails will work fine!

**Comment by Robby2023** [comment]
Perfect
