### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by josemhdez** [Inevio/Gmail#72]
When I search, the total ammount of emails after this search still has the same number as the total inbox. Furthermore, when I start going back to these first emails, at one point Im not able to continue searching for previous emails.
![image](https://user-images.githubusercontent.com/12035376/35105183-44a27cbe-fc6b-11e7-8b75-583e6d06004c.png)

**Comment by burhan-project-manager** [comment]
I understand first point but can you please explain following in little more details?

> 
Furthermore, when I start going back to these first emails, at one point Im not able to continue searching for previous emails.

**Comment by josemhdez** [comment]
When there are no more emails which fit on the search I made, the arrow to go to older emails change to unclickable

**Comment by burhan-project-manager** [comment]
Ok i understand. 

@icastillejogomez we have discussion about pagination in some older issue.

We were calling `usersThreadsList` to get total counts, but this API returns estimated count, so @icastillejogomez  develop two other APIs `usersGetProfile` and `usersLabelsGet` to get actual count.

But in case of search we are not getting any count details. We need a way to get total accounts against searched query.

**Comment by icastillejogomez** [comment]
It's no possible. The only way to solve it is eliminate the "of X" text and wait to get the last page, then print "of X" text.

**Comment by burhan-project-manager** [comment]
We don't have total count in case of search so we can't calculate current page also. 

But next/previous buttons will work fine.

Check now
![image](https://user-images.githubusercontent.com/28291997/35333313-218877dc-0130-11e8-87bc-88bf51cca8f9.png)

**Comment by icastillejogomez** [comment]
You have to print 1 - 20  ;  21 - 40 and when you get the last page then print in **all** pages 

Before I get the last page:

`1 - 20`
`21 - 40`

After I get the last page:

`1 - 20 of <total_messages_here>`
`21 - 40 of <total_messages_here>`

**Comment by burhan-project-manager** [comment]
Pagination implemented in search.
