### ISSUE TITLE
Mark as read/ Unread page numeration bug

### ISSUE THREAD

**Issue by josemhdez** [Inevio/Gmail#73]
If you go some pages back in order to see older emails, and you select all of them even to mark them as read or unread, after doing it, the screen show you the first emails of inbox or sent etc instead of the ones you marked. Also the numeration still shows the page you were before eventhough the messages shown are the latest ones.

This image is after I do all the process, showing how it ends up showing the latest emails with the wrong page numeration:

![image](https://user-images.githubusercontent.com/12035376/35107491-62ab955a-fc71-11e7-8606-28e7ee645c2c.png)

**Comment by burhan-project-manager** [comment]
It is fixed!

**Comment by jorge9200** [comment]
@burhan-project-manager pagination is now going so slow :S

**Comment by burhan-project-manager** [comment]
Yes server response is slow but sometimes it works fast .
