### ISSUE TITLE
Padding

### ISSUE THREAD

**Issue by josemhdez** [Inevio/Gmail#74]
When writing a new email, there is less paddy than Gmail use.

![image](https://user-images.githubusercontent.com/12035376/35107781-172533a6-fc72-11e7-81bc-394d28c8f9a5.png)

VS

![image](https://user-images.githubusercontent.com/12035376/35107822-340735be-fc72-11e7-9fc4-210289b9f4ee.png)

**Comment by burhan-project-manager** [comment]
It is done!

**Comment by josemhdez** [comment]
Yes, now it's fixed thanks, but now we have got the problem of issue #79 which can be related.
