### ISSUE TITLE
Emails with videos embeded aren´t shown correctly

### ISSUE THREAD

**Issue by josemhdez** [Inevio/Gmail#75]
This is the typical Youtube maiol for the channels you are subscribed. On the appp you see it like this:

![gmail mal correos con videos youtube](https://user-images.githubusercontent.com/12035376/35140038-02c480f4-fcf6-11e7-8fa8-b685d373d15e.JPG)

While in Gmail its shown like this:

![image](https://user-images.githubusercontent.com/12035376/35140108-4c7cf0dc-fcf6-11e7-9190-9d2957640fd5.png)

**Comment by burhan-project-manager** [comment]
@josemhdez  please forward youtube email to me at burhan.project.manager@gmail.com

**Comment by josemhdez** [comment]
Email sent :)

**Comment by burhan-project-manager** [comment]
Forwarded email is not loading. We will look into this problem soon.

![image](https://user-images.githubusercontent.com/28291997/35221966-07614bce-ff9e-11e7-83c6-4ab166f5db23.png)

**Comment by burhan-project-manager** [comment]
It is fixed now!

![image](https://user-images.githubusercontent.com/28291997/35274064-85b48586-005c-11e8-9a01-5f4803ce7a3f.png)
