### ISSUE TITLE
Compose New email bug?

### ISSUE THREAD

**Issue by josemhdez** [Inevio/Gmail#76]
I started the app and expanded it a bit, then I clicked on compose and the image of new email was like this image.

![image](https://user-images.githubusercontent.com/12035376/35154097-2966df4e-fd29-11e7-85a9-5aed9b8a1ae7.png)

**Comment by josemhdez** [comment]
I´ve refreshed the page and now works correctly. What could have happenned?

**Comment by burhan-project-manager** [comment]
That's strange, we will look into this problem soon.

**Comment by burhan-project-manager** [comment]
We are not getting same error again!
If you get it again, please post here with steps that you took.
