### ISSUE TITLE
Attached design is not good

### ISSUE THREAD

**Issue by josemhdez** [Inevio/Gmail#77]
There is a problem with the view of the attachments when creatibg a new email. Thare are problems when you have a signature of email and when the email is long enough to reach the body of the attachment.

![gmail ajunto con firma](https://user-images.githubusercontent.com/12035376/35154222-b9bd2ad0-fd29-11e7-8e9d-531b05bcc3f6.JPG)
![gmail adjunto body largo sin firma](https://user-images.githubusercontent.com/12035376/35154224-b9dc48a2-fd29-11e7-907b-4eb20bdacdb5.JPG)

**Comment by burhan-project-manager** [comment]
Fixed!

![image](https://user-images.githubusercontent.com/28291997/35276670-f2840b56-0065-11e8-8f34-5a4034272624.png)
