### ISSUE TITLE
Problems whe you add wrong email to recipient

### ISSUE THREAD

**Issue by josemhdez** [Inevio/Gmail#78]
When you add to recepient a wrong email (or a url for example) it shows you this text with red background which is correct. Once you erase this text, the red background remains there:

![image](https://user-images.githubusercontent.com/12035376/35154807-dfa80d44-fd2b-11e7-8320-30bccb8ea369.png)

It disappear once you introduce a correct new email but it should be removed once you erase the wrong one.

**Comment by burhan-project-manager** [comment]
Once you erase wrong text BUT you are still in editing mode, it is showing red background.
But if you click anywhere else with empty tag, it will remove that red background.

I think it is working fine!
