### ISSUE TITLE
The space between the lines in compose is too big

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#8]
Each line you write is very separate from one another, which causes you to think it looks good but the receiver reads everything very close.

horbito gmail:
![image 5](https://user-images.githubusercontent.com/8724844/32488237-44b998ba-c3ac-11e7-9f54-f6ee6d4a8fc9.png)

native gmail:
![image 6](https://user-images.githubusercontent.com/8724844/32488253-50b6df74-c3ac-11e7-85bc-403641ff9f2f.png)

**Comment by burhan-project-manager** [comment]
It is done!

**Comment by jorge9200** [comment]
fixed
