### ISSUE TITLE
CID Images Error in Safari

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/Gmail#81]
<img width="1030" alt="captura de pantalla 2018-01-23 a las 1 29 11" src="https://user-images.githubusercontent.com/16567802/35251756-0808ce6e-ffdd-11e7-80d7-dc8ac08997c2.png">
<img width="284" alt="captura de pantalla 2018-01-23 a las 1 29 27" src="https://user-images.githubusercontent.com/16567802/35251757-0823c8b8-ffdd-11e7-875e-d91dece99158.png">

**Comment by burhan-project-manager** [comment]
In Gmail message response we are getting GID for some images as source.

![image](https://user-images.githubusercontent.com/28291997/35278106-cb32f2c4-006a-11e8-9418-ac19afaf8cfc.png)

But in actual Gmail source is different:

![image](https://user-images.githubusercontent.com/28291997/35278139-e1a546e2-006a-11e8-9db7-3829d4c4943d.png)

We couldn't find any relation of those GID with attachments also.

**Comment by icastillejogomez** [comment]
tomorrow I'll see it with @javiergarmon
