### ISSUE TITLE
The email doesn't look the same as original

### ISSUE THREAD

**Issue by tavi004** [Inevio/Gmail#82]
On the left is how it should look and on the right gmail for horbito.

![image](https://user-images.githubusercontent.com/3248361/35269053-2a7dbe3e-002b-11e8-8c2f-caf81450a48b.png)

**Comment by burhan-project-manager** [comment]
Please check again, it was fixed!

**Comment by tavi004** [comment]
The mail still looks the same. Looks like the font it doesn't load
![image](https://user-images.githubusercontent.com/3248361/35286536-92df0a7a-0060-11e8-95d1-647d5d5a5fe0.png)

**Comment by burhan-project-manager** [comment]
May be it is custom font and google rendering that custom font.

Need to see it. @tavi004  please forward that email to me burhan.project.manager@gmail.com

**Comment by tavi004** [comment]
Done!

**Comment by burhan-project-manager** [comment]
I don't know if it is browser or cache issue. But we are getting it correctly.

![image](https://user-images.githubusercontent.com/28291997/35333256-dff6b59a-012f-11e8-892b-4d3cc0a91be7.png)
