### ISSUE TITLE
Weird typo 

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Gmail#83]
![image](https://user-images.githubusercontent.com/1384919/35269843-8c024204-002d-11e8-9254-9bba15eb080c.png)

**Comment by burhan-project-manager** [comment]
@Robby2023  please explain what actually do you want to resolve in this?

**Comment by Robby2023** [comment]
The texts I've indicated should be Lato

**Comment by burhan-project-manager** [comment]
@Robby2023  those texts should be Lato or Arial? 
Because someone directed us to to change Lato to Arial on some pages.

Also Gmail uses Arial.

BTW we have changed it to Arial.

**Comment by tavi004** [comment]
Only the content of the emails and the list of emails should be in Arial, the texts of the UI should be Lato like before, where everything looked right

**Comment by burhan-project-manager** [comment]
Lato Implemented!

**Comment by tavi004** [comment]
The accounts texts is stil Arial.
![image](https://user-images.githubusercontent.com/3248361/35381706-6f13bace-01bd-11e8-80e2-ef68cdb81b94.png)


This contextual menu doesn't have the same design as the others, please unify it under the same design and same text as the "More", and give a little more padding between each option.
![image](https://user-images.githubusercontent.com/3248361/35381814-c367b5da-01bd-11e8-924d-7b03233fdd64.png)
![image](https://user-images.githubusercontent.com/3248361/35381824-c981294c-01bd-11e8-9e23-e8eff4c34aa8.png)

**Comment by tavi004** [comment]
The email lost the style: 
![image](https://user-images.githubusercontent.com/3248361/35381952-24170cd2-01be-11e8-997a-f8cb9448aa61.png)
![image](https://user-images.githubusercontent.com/3248361/35381963-2d765800-01be-11e8-9d71-242b7f5684ef.png)

**Comment by burhan-project-manager** [comment]
Implemented Lato font family and same menu style.

![image](https://user-images.githubusercontent.com/28291997/35389549-ef1553b8-01f9-11e8-8228-3dc1076c98f3.png)

**Comment by burhan-project-manager** [comment]
Can you forward that email to me from Gmail, it is looking strange.

**Comment by tavi004** [comment]
Still has bold text unlike the other contextual menus, remove the bold
![image](https://user-images.githubusercontent.com/3248361/35442202-a74d4ee8-02a6-11e8-87e8-f594f5a5428b.png)

**Comment by tavi004** [comment]
Here the font size should be 13px

![image](https://user-images.githubusercontent.com/3248361/35442238-d1260f84-02a6-11e8-8b95-7604e16e4a72.png)

**Comment by burhan-project-manager** [comment]
@tavi004 i have received email in Gmail like this:

![image](https://user-images.githubusercontent.com/28291997/35497152-d05e69c0-04ea-11e8-82dd-d5f59b5e23ae.png)

It seems you have sent it from Horbito. Can you please send it from Gmail?

**Comment by tavi004** [comment]
done!

**Comment by burhan-project-manager** [comment]
We have received it in good manner.

![image](https://user-images.githubusercontent.com/28291997/35505704-bed371be-0508-11e8-97d5-d1498eae7d35.png)

We are not able to trace that issue because we can't see it
