### ISSUE TITLE
Recipients not showing

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Gmail#84]
When I receive an email with several recipients in Gmail it shows this way:

![image](https://user-images.githubusercontent.com/1384919/35269922-cf0b0a68-002d-11e8-9111-57d3e8a326d9.png)

However, on the app it shows like this:

![image](https://user-images.githubusercontent.com/1384919/35269946-dd88e70e-002d-11e8-987c-d49478809206.png)

However if I click in the dropdown it shows several people:

![image](https://user-images.githubusercontent.com/1384919/35269982-f2ac75ec-002d-11e8-9316-6705e9826988.png)

**Comment by burhan-project-manager** [comment]
It is done!

**Comment by Robby2023** [comment]
It's still not showing info of the recipients unless I click on the dropdown:

![captura de pantalla 2018-01-24 a las 17 21 29](https://user-images.githubusercontent.com/1384919/35343515-2425adde-012b-11e8-8768-da9d28f18db6.png)

There it should say "To me, Borja, Nacho..."

If I click in the dropdown you can see there are more recipients:

![captura de pantalla 2018-01-24 a las 17 21 36](https://user-images.githubusercontent.com/1384919/35343570-44357ae6-012b-11e8-83ea-2a3161f5de10.png)

**Comment by burhan-project-manager** [comment]
It is done now!

**Comment by Robby2023** [comment]
It is indeed working now although there is a small bug, the first name after "me" appears bold:

![image](https://user-images.githubusercontent.com/1384919/35399398-68466d72-01f4-11e8-9351-c584233ff2cf.png)

**Comment by burhan-project-manager** [comment]
Are you still facing this issue? Because we are not getting this bug again.

**Comment by Robby2023** [comment]
No, looks good now
