### ISSUE TITLE
I can't "Reply to all"

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Gmail#85]
I'm trying to "Reply to all" in an email I've received but it's not showing that option:

![image](https://user-images.githubusercontent.com/1384919/35270107-64f7737c-002e-11e8-9c04-194237d61d3b.png)

If I click in the dropdown it shows several recipients:

![image](https://user-images.githubusercontent.com/1384919/35270123-7588c5ba-002e-11e8-9df3-cd4a68ac4ddf.png)

**Comment by burhan-project-manager** [comment]
**Reply to all** feature is added

**Comment by Robby2023** [comment]
It seems it's not working properly, when I click on "Reply to all" and add a message, when I click "Send" it shows "Sending..." but nothing happens.

**Comment by burhan-project-manager** [comment]
There is a problem with API, created an issue #88  for that.

**Comment by icastillejogomez** [comment]
issue [#88](https://github.com/Inevio/Gmail/issues/88) answered!

**Comment by burhan-project-manager** [comment]
Issue fixed!

**Comment by Robby2023** [comment]
If you select "reply to all" it also includes the sender which doesn't make any sense:

![image](https://user-images.githubusercontent.com/1384919/35573132-7322e3de-05d6-11e8-8d07-f43a76a33610.png)

**Comment by burhan-project-manager** [comment]
Yes you are right, it is also fixed.
