### ISSUE TITLE
Details menu has some bugs

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Gmail#87]
Here is how it shows in Gmail:

![image](https://user-images.githubusercontent.com/1384919/35281791-1ac39530-0054-11e8-8f65-d81d338dc3aa.png)

Here is how it appears in the app:

![image](https://user-images.githubusercontent.com/1384919/35281853-407c2f4e-0054-11e8-86fc-ea6ff67a75a6.png)

- The typography and text size is incorrect
- The data shown is incomplete (it should show email address)
- Date format is incorrect

**Comment by burhan-project-manager** [comment]
Text size, additional data and date format corrected.

**Comment by Robby2023** [comment]
The design is perfect now! Good job. However, text is not selectable which is a bit annoying if I want to select the email or name of any of the recipients, would it be possible to make it selectable?

**Comment by burhan-project-manager** [comment]
We have tried to enable selection and copy but restrictions are imposed Globally.

**Comment by jorge9200** [comment]
you can make it selectable for firefox (here is the problem) by adding this class!

![image](https://user-images.githubusercontent.com/8724844/35399750-4dd5e0b6-01f5-11e8-8873-a06f0b118f7f.png)

wz-selectable to the spans where is the text

**Comment by burhan-project-manager** [comment]
Implemented, but still right click is disabled!

**Comment by jorge9200** [comment]
fixed
