### ISSUE TITLE
bad "to" field when I try to use 'reply to all' feature

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/Gmail#89]
![bugreplytoall1](https://user-images.githubusercontent.com/16567802/35469546-eaaddb68-0336-11e8-87ef-4e52dfea22b2.png)
![bugreplytoall2](https://user-images.githubusercontent.com/16567802/35469547-eac353a8-0336-11e8-8810-b515e1c1516e.png)
video: http://wz.io/f/ppTpfniW

**Comment by burhan-project-manager** [comment]
It is fixed
