### ISSUE TITLE
Email intern scroll haves lot of lag

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#9]
Can be improved?

**Comment by burhan-project-manager** [comment]
Can you show me any screen of what you are talking about?

**Comment by jorge9200** [comment]
![image](https://user-images.githubusercontent.com/8724844/32491293-76247fe6-c3b6-11e7-89e6-bfd5bbf5831e.png)

That scroll

**Comment by burhan-project-manager** [comment]
From where it is lagging? It is looking good...

**Comment by jorge9200** [comment]
I'll send you a video by Skype

**Comment by jorge9200** [comment]
Please @Robby2023 add here the video

**Comment by javiergarmon** [comment]
This probably is an issue of the platform. Please, let me check it and discover the source.

**Comment by jorge9200** [comment]
also solved on script.js sended via skype
