### ISSUE TITLE
Is not showing the attachments on one email

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#90]
Email on horbito:
![imagen](https://user-images.githubusercontent.com/8724844/35515605-f494af1a-0509-11e8-8228-07a69c36b806.png)
(no attachments)

Email on Outlook:
![imagen](https://user-images.githubusercontent.com/8724844/35515705-251a11f2-050a-11e8-86ab-c8ea15cbd19e.png)
(with attachments)

Are we losing them? Or just not showing them?

Sara has forwarded the email to you.

**Comment by jorge9200** [comment]
She has sent it from both sides "from gmail" and "from horbito"

**Comment by burhan-project-manager** [comment]
I think it is due to #91
