### ISSUE TITLE
Attachment not sending when forwarding email

### ISSUE THREAD

**Issue by burhan-project-manager** [Inevio/Gmail#91]
When we forward and email that has attachment, that attachment is not attaching with forwarded email.

Reason:
When we send an email, we attach files using Horbito APIs. So how to forward same attachment with forwarded email?

**Comment by jorge9200** [comment]
You have to call getAttachments() with the `message id` and the `attachment id`

![image](https://user-images.githubusercontent.com/8724844/35701347-f8fee0d2-0795-11e8-92fe-9936a51cf034.png)

then you forward the thread with the attachment.

Does it makes sense to you?

**Comment by burhan-project-manager** [comment]
That API of `getAttachment` is returning/downloading contents of attachment.
If an attachment has 5 MB data, it means to forward email we will download 5 MB data and then upload it with message?

I think `usersDraftCreate` API should accept attachment ID and forward it from server.
We have tried to send attachment ID but got Error "EMPTY FILE ID"

**Comment by jorge9200** [comment]
For a first version we are going to introduce an alert() when you try to forward an email with attachments saying "You will have to download the attachments and reattach to de message to send this attachments" (something like that)

**Comment by burhan-project-manager** [comment]
Alert Added!
