### ISSUE TITLE
Loading... problem

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Gmail#92]
We have found that if the attachment has no name, it is included on body not on the corresponding place.

This is causing Loading... problem, or almost one cause of it.

**Comment by burhan-project-manager** [comment]
@jorge9200  do you have any email that has attachment with no name? Please forward it so that we can inspect it.

**Comment by jorge9200** [comment]
The tester gave me this video.

[error_attachment.mov.zip](https://github.com/Inevio/Gmail/files/1688589/error_attachment.mov.zip)

**Comment by jorge9200** [comment]
You can see there how to replicate

**Comment by jorge9200** [comment]
Because if I forward again to you, I think Google fix it. So please try to replicate yourself the error.

**Comment by jorge9200** [comment]
I'm sorry, the problem is not the attachment has no name. The problem is the body has no name

**Comment by burhan-project-manager** [comment]
It is fixed, please check.

We don't have any message like that but according to video we have fixed it. Please confirm
