### ISSUE TITLE
An email is not showing

### ISSUE THREAD

**Issue by saragsc** [Inevio/Gmail#94]
This email is not showing (the one from "yo, Info(7)")

Native:
![imagen](https://user-images.githubusercontent.com/36300363/36200856-44ac0d42-117e-11e8-824b-10f3d17db284.png)

Horbito:
![imagen](https://user-images.githubusercontent.com/36300363/36200914-7dd17dc8-117e-11e8-8379-ea31ff9dd6f1.png)

And Google api is returning it:
![imagen](https://user-images.githubusercontent.com/36300363/36200951-96847cbc-117e-11e8-8ba5-b5677e67d4c7.png)

I have resended to you burhan

**Comment by burhan-project-manager** [comment]
@saragsc we are not able to re-produce this bug.
We are just injecting all data that we get via your APIs.

Have have added a console  "saragsc test" that displays all data returned by `usersThreadsList` api.  Can you please forward that consoled data here?

**Comment by jorge9200** [comment]
ok
